Additional SonicWall CDF's #2
trendmicro/tm-v1-detection-models pull request #8
Opened 2024-12-19 17:41 UTC by christian-geollegue

2nd batch of SonicWall additional CDF's

2024-12-20 19:40 UTC, AmbientPlatypus submitted a review, later dismissed
Batch add custom detection models for Sonicwall

2024-12-20 19:42 UTC, AmbientPlatypus commented
@christian-geollegue Your commit wasn't signed... You'll need to redo the PR but with a signed commit.

2024-12-20 19:42 UTC, AmbientPlatypus requested changes
Looks good but the commit wasn't signed.

2025-01-14 08:06 UTC, christian-geollegue commented
Hi, sorry for I am quite confused. What do I need to do to have the following PR signed? Thank you!

2025-01-15 01:52 UTC, closed without merging